const addTrajetObjects = {
    AddTrajetButton: 'p.my-auto.ps-2:contains("Proposer un trajet")',
    Villededepart: 'input[placeholder="Saisir la ville ou adresse"]',
    villedearrivee: 'input[placeholder="Saisir la ville ou adresse"]',
    DateDepart: 'input[type="date"]',
    DateArrivee: 'input[type="date"]',
    dayoption1: 'label[for="option1"]',
    nightoption2: 'label[for="option2"]',
    dayoption3: 'label[for="option3"]',
    nightoption4: 'label[for="option4"]',
    moyentransport: 'label[for="camion"]',
    maxlength: 'input[name="max_length"]',
    maxwidth: 'input[name="max_width"]',
    maxheight: 'input[name="max_height"]',
    maxweight: 'label[for="-5kG"]',
    collecthandtohandyes: '#r1',
    collecthandtohandno: '#r2',
    collecrelaisyes: '#r3',
    collecrelaisno: '#r4',
    delivraisonhandtohandyes: '#r5',
    delivraisonhandtohandno: '#r6',
    delivraisonrelaisyes: '#r7',
    delivraisonrelaisno: '#r8',
    submitbutton: 'button[type="submit"]',
    successMessage: 'div[role="alert"]',
    errorMessages: '.invalid-feedback', 
    submitgoogleaddress: '.pac-item', 

    }
export default addTrajetObjects;